replicaCount: 2

image:
  repository: gabriel1304/flask-app
  tag: latest
  pullPolicy: IfNotPresent

containerPort: 5000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: nginx
  host: flask.local
  path: /
  pathType: Prefix

resources: {}

serviceAccount:
  create: false
  name: ""

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
