name: CI/CD com Helm

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: gabriel1304/flask-app
      IMAGE_TAG: latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Login no Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build da imagem
        run: |
          docker build -t $IMAGE_NAME:$IMAGE_TAG .

      - name: Push para Docker Hub
        run: |
          docker push $IMAGE_NAME:$IMAGE_TAG

      - name: Instalação do Helm
        uses: azure/setup-helm@v3

      - name: Instalação do kubectl
        uses: azure/setup-kubectl@v3

      - name: Configurar kubeconfig (Minikube)
        run: |
          echo "${{ secrets.KUBECONFIG_CONTENT }}" | base64 -d > kubeconfig 

      - name: Deploy com Helm
        run: |
          helm upgrade --install flask-app ./k8s/flask-app --kubeconfig kubeconfig

